Predev
WildCodeSchool/04-24-poec-bdx-java_projet-tu-quoque pull request #118
Opened 2024-06-13 08:38 UTC by NeliaCou

2024-06-14 13:49 UTC, peacepilou requested changes

2024-06-14 13:49 UTC, peacepilou commented on src/app/modules/shared/services/api-ressource/api-ressource.service.ts
> +  // }
comments

2024-06-14 13:49 UTC, peacepilou commented on src/app/modules/shared/services/uploadFile/upload-to-firebase.service.ts
> +  }
pas fou voir pour le refacto en | async

2024-06-14 13:49 UTC, peacepilou commented on src/app/modules/user/modules/character/modules/character-creation/components/features/new-character/new-character.component.ts
> +        console.log('Upload process finished');
log

2024-06-14 13:49 UTC, peacepilou commented on src/app/modules/user/modules/character/modules/character-creation/components/features/new-character/new-character.component.ts
> +  }
a refacto en full observable

2024-06-14 13:49 UTC, peacepilou commented on src/app/modules/user/modules/character/modules/character-management/components/features/character-page/character-page.component.ts
> +    this.characterSubscription = this._characterService.getUserCharacterById$(id).subscribe(response => this.foundCharacter = response);
| async ?

2024-06-14 13:49 UTC, peacepilou commented on src/app/modules/user/modules/table/modules/table-creation/components/features/new-table/new-table.component.ts
> +          .catch(err => {
phacoooo

2024-06-14 13:49 UTC, peacepilou commented on src/app/modules/user/modules/table/modules/table-management/components/features/characters-to-accept/characters-to-accept.component.ts
> +        (this.characterOnHoldList = characterList), console.log(this.characterOnHoldList);
log

2024-06-21 09:27 UTC, Phalenopsis commented on src/app/modules/character-sheet/components/statistics-components/ui/statistics-dice/statistics-dice.component.ts
> +    });
parce que dans la méthode du dessous, je passe isVisible à true, indépendamment de l'observable observé initialement.
je pourrais passer par un behaviour subject pour utiliser le pipe async, mais cela m'oblige quand même à subscribe l'observable initial.
se débarrasser d'un subscribe pour utiliser un pipe async tout en étant obligé d'utiliser un subscribe en plus me parait contre productif.

2024-06-21 09:39 UTC, Phalenopsis commented on src/app/modules/character-sheet/components/market/feature/market-place/market-place.component.ts
> +  }
j'ai besoin de purse (non observable) dans l'affichage (gnagnagna pipe async) ET dans une méthode plus bas

2024-06-21 09:40 UTC, Phalenopsis commented on src/app/modules/character-sheet/shared/services/character-sheet.service.ts
> +    ).subscribe((id: number) => {
la sheet est cassée à certains endroits dans cette version. je regarde pour faire la modif dans la version ou les bugs sont en partie fixés

2024-06-25 12:24 UTC, peacepilou approved these changes

2024-06-25 12:24 UTC, merged